from pathlib import Path
from jinja2 import Environment
from markupsafe import Markup
p=Path('portal/app/templates/_macros.html')
env=Environment(autoescape=True);env.filters.update(local=str,filesize=str);mod=env.from_string(p.read_text()).module
parts=[]
for theme in ('light','dark'):
    parts.append(f'<section data-bs-theme="{theme}" class="p-4" style="background:var(--bs-body-bg);color:var(--bs-body-color)"><h2>{theme}</h2>')
    parts.append(str(mod.page_header('Dokumente finden','Referenz der produktiven Jinja-Komponenten','/example/new','Neues Dokument',caller=lambda:Markup(mod.action_menu(caller=lambda:Markup('<button class="btn btn-outline-secondary" type="button" disabled>Export (nicht verfügbar)</button>'))))))
    parts.append(str(mod.filter_bar(expanded=True,caller=lambda:Markup('<label for="q-'+theme+'">Suche</label><input class="form-control" id="q-'+theme+'" type="search"><button type="button" class="btn btn-outline-primary mt-2">Suchen</button>'))))
    parts.append(str(mod.active_filter('Ordner','Personal'))+str(mod.result_summary(3)))
    for tone,label in [('neutral','Entwurf'),('info','Wartet auf nächste Person'),('success','Abgeschlossen'),('warning','Ihre Bestätigung fehlt'),('error','Abgelehnt')]:parts.append(str(mod.status_chip(label,tone)))
    parts.append(str(mod.detail_meta([('Verantwortlich','Anna Muster'),('Stand','Heute')])))
    parts.append('<h3>Leer</h3>'+str(mod.empty_state('Keine passenden Dokumente','Suche zurücksetzen oder Ordner wechseln.','/example','Filter zurücksetzen')))
    parts.append('<h3>Laden</h3><div class="ds-loading" role="status"><i class="fa-solid fa-spinner fa-spin" aria-hidden="true"></i>Dokumente werden geladen …</div><h3>Fehler</h3><div class="alert alert-danger" role="alert">Speichern fehlgeschlagen. Ihre Eingaben bleiben erhalten. Bitte erneut versuchen.</div><label for="name-'+theme+'">Name</label><input id="name-'+theme+'" class="form-control is-invalid" value="" aria-invalid="true" aria-describedby="err-'+theme+'"><p id="err-'+theme+'" class="text-danger">Bitte einen Namen eingeben.</p><h3>Disabled</h3><button class="btn btn-outline-secondary" type="button" disabled>Veröffentlichen (Berechtigung fehlt)</button>')
    parts.append('<h3>Mobile Tabelle</h3><table class="table ds-mobile-table"><thead><tr><th scope="col">Dokument</th><th scope="col">Status</th><th scope="col">Aktionen</th></tr></thead><tbody><tr><td data-label="Dokument">Langer Dokumenttitel mit mehreren Wörtern und umfangreicher Beschreibung</td><td data-label="Status">'+str(mod.status_chip('Entwurf'))+'</td><td data-label="Aktionen"><a href="/example" class="btn btn-outline-secondary">Ansehen</a></td></tr></tbody></table><h3>Karte und Dialog</h3><article class="card"><div class="card-body"><h4>Beispieldokument</h4><p>Titel, kurze Beschreibung und eine Handlung.</p><button type="button" class="btn btn-outline-secondary" onclick="document.getElementById(\'dialog-'+theme+'\').showModal()">Dialog öffnen</button></div></article><dialog id="dialog-'+theme+'"><form method="dialog"><h4>Archivieren?</h4><p>Das Dokument bleibt lesbar und wird schreibgeschützt.</p><button value="cancel" autofocus>Abbrechen</button><button value="confirm">Archivieren</button></form></dialog></section>')
html='''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Designsystem – Komponentenreferenz</title><link rel="stylesheet" href="../portal/app/static/vendor/bootstrap/bootstrap.min.css"><link rel="stylesheet" href="../portal/app/static/vendor/fontawesome/css/all.min.css"><link rel="stylesheet" href="../portal/app/static/design-system.css"></head><body><main><h1 class="p-4">Komponentenreferenz</h1>'''+''.join(parts)+'</main></body></html>'
Path('docs/design-system-reference.html').write_text(html)
