const fs = require('fs'), vm = require('vm'), assert = require('assert');
const source = fs.readFileSync('portal/app/static/form-fill.js', 'utf8');
const start = source.indexOf('  function focusQuestion(qid)');
const end = source.indexOf('  /* --- Bedingungen', start);
let focused = null, shown = null, clicked;
const page = {_hidden:false};
const native = {type:'date',disabled:false, closest:()=>null,getClientRects:()=>[]};
const disabled = {type:'text',disabled:true};
const proxy = {type:'text',disabled:false,closest:()=>null,getClientRects:()=>[1],focus(){focused='proxy';},scrollIntoView(){},attrs:{'aria-describedby':'existing'},getAttribute(n){return this.attrs[n];},setAttribute(n,v){this.attrs[n]=v;}};
const question = {dataset:{serverError:'error-date'},closest:()=>page,querySelectorAll:()=>[native,disabled,proxy],focus(){focused='question';},scrollIntoView(){}};
native.setAttribute=()=>{};native.getAttribute=()=>'';disabled.setAttribute=()=>{};disabled.getAttribute=()=>'';
const form = {querySelectorAll:()=>[question],addEventListener(name,callback){if(name==='click')clicked=callback;}};
const context={document:{getElementById:()=>question},form,pages:[{},page],show(i){shown=i;}};
vm.createContext(context);vm.runInContext(source.slice(start,end),context);
assert.equal(proxy.attrs['aria-invalid'],'true');assert.equal(proxy.attrs['aria-describedby'],'existing error-date');
let prevented=false;
clicked({target:{closest:()=>({dataset:{formError:'date'}})},preventDefault(){prevented=true;}});
assert(prevented);assert.equal(shown,1);assert.equal(focused,'proxy');
proxy.getClientRects=()=>[];context.focusQuestion('date');assert.equal(focused,'question');
page._hidden=true;shown=null;context.focusQuestion('date');assert.equal(shown,null);
console.log('Public UX error navigation tests passed');
